---
# tasks file for usbip-server

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works on Debian or derivatives like Ubuntu'
  when: ansible_os_family != 'Debian'
  tags: ['always']

- import_tasks: install.yml
  tags: ['usbip-server', 'usbip-server-install']

- import_tasks: configure.yml
  tags: ['usbip-server', 'usbip-server-configure']

- import_tasks: service.yml
  tags: ['usbip-server', 'usbip-server-service']

#- include_tasks: export-devices.yml
  #when: usbip__mode == 'server' and usbip__service_enabled|bool
  #tags: ['usbip', 'usbip-export-devices']
